### DISCUSSION TITLE
Epic: Add New Providers Configuration Block For Fine Grained Controls

### DISCUSSION THREAD

**Discussion by da-moon** [aaif-goose/goose#1185] [Ideas]
### Context

To enable finer control over how we connect to LLM providers—and to introduce
the capability to throttle API calls—we propose a new, unified `providers`
configuration block. This block will group all provider-specific parameters
(such as `name`, `type`, `api_base`, `temperature`, `top_p`, `cache`,
`max_tokens`, and `additional_headers`) and include a new configurable rate
limiting mechanism.

For this epic, our focus is on implementing a "simple" rate
limiting strategy; while we will document a token bucket approach for future
work, that remains out of scope.

I wanted to start a discussion around this and with your blessings , I can get started on this change

### Value

- **Centralization:** Consolidate all provider settings into a single
  configuration block.
- **Reliability:** Reduce rate limit errors by allowing users to set API call
  and token usage thresholds.
- **User Empowerment:** Enable users to fine-tune provider interactions
  according to their quota limits.
- **Incremental Delivery:** Break the work into small, atomic PRs so that value
  can be delivered and merged quickly.
- **Foundation for Future Work:** Establish a baseline for advanced rate
  limiting (e.g. token bucket) in future iterations.

### Acceptance Criteria

- **New Providers Configuration Block:**
  - Introduce a unified `providers` section containing:
    - Provider base settings: `name`, `type`, `api`, `temperature`, `top_p`,
      `cache`, `max_tokens`, and `additional_headers`.
    - A new `ratelimit` sub-section (initially supporting the "simple"
      strategy).
- **Configuration Parser Updates:**
  - Extend the configuration parser to support and validate the new `providers`
    block.
  - Maintain backward compatibility with existing configuration keys.
- **Simple Rate Limiter Implementation:**
  - Implement a simple rate limiting mechanism that enforces limits on requests
    and tokens per period.
  - Integrate a retry mechanism (with configurable delay and max retries) for
    handling rate limit errors.
  - Apply this logic within the provider API request workflow.
- **Testing and Documentation:**
  - Develop unit tests to cover the new configuration block and rate limiting
    behavior.
  - Update project documentation with an example YAML configuration (see
    Additional Context below).
  - Document the token bucket approach as a potential future enhancement.

### Measurement

- Reduction in rate limit errors during high-volume operations.
- Increased stability and success rate of provider API calls.
- Positive feedback in issue discussions, PR reviews, and user reports.

### Persona(s)

- **Goose Users:** Especially those interfacing with high-volume LLM providers.
- **DevOps/Engineering Teams:** Teams requiring predictable and controlled API
  usage.
- **Contributors:** Developers interested in enhancing configuration
  flexibility and system robustness.

### In Scope

- **PR 1:**
  - Introduce a new `providers` configuration element that groups all
    provider-specific parameters into a single block.
  - Include fields for basic settings: `name`, `type`, `api`, `temperature`,
    `top_p`, `cache`, `max_tokens`, and `additional_headers`.
- **PR 2:**
  - Update the configuration parser to recognize and validate the new
    `providers` block.
  - Ensure legacy parameters (e.g. `GOOSE_PROVIDER`) are either mapped or
    properly deprecated.
- **PR 3:**
  - Add new configuration fields under `providers` to support the simple rate
    limiting mechanism.
  - This includes the following sub-fields within `ratelimit`:
    - `type: simple`
    - `config.requests` (with `limit` and `period_seconds`)
    - `config.tokens` (with `limit` and `period_seconds`)
    - `config.retry` (with `delay_seconds` and `max_retries`)
- **PR 4:**
  - Implement the simple rate limiting logic and integrate it into the provider
    API request workflow.
- **PR 5:**
  - Develop unit tests for both the new providers configuration and the simple
    rate limiting mechanism.
- **PR 6:**
  - Update the documentation with a comprehensive example YAML configuration.
  - Document the token bucket approach as a future enhancement (out of scope
    for this epic).

### Out of Scope

- Implementation of alternative rate limiting strategies (e.g., token bucket,
  sliding window).
- Dynamic adjustments based on real-time API response headers.
- Automatic fallback to alternative providers upon rate limit errors.
- Modifications to existing extension configurations outside the new
  `providers` block.

### Complexities

- Maintaining backward compatibility with the current configuration scheme.
- Coordinating changes across the configuration parser, API request workflow,
  and rate limiting logic.
- Ensuring that the retry and delay mechanisms are effective without
  introducing significant performance penalties.

### Additional Context

Below is an example YAML configuration that combines existing configuration
elements with the new `providers` block and a simple rate limiting mechanism:

```yaml
GOOSE_PROVIDER: anthropic
GOOSE_MODEL: claude-3-5-sonnet-latest
extensions:
  computercontroller:
    enabled: true
    name: computercontroller
    type: builtin
  developer:
    enabled: true
    name: developer
    type: builtin
# NOTE: proposed changes
providers:
  - name: "claude-3-5-sonnet-latest" # Name has to be unique. matches `GOOSE_MODEL`
    type: "anthropic" # We can have other types such as openai ; the type would enable us to create multiple providers, e.g have backup providers from openrouter or we can add other openai compliant LLM inference api providers such as perplexity; it matches GOOSE_PROVIDER
    api: "https://api.anthropic.com/v1/messages" # allow customization of base url which can help in cases such as using openai compliant endpoints
    temperature: 0.3 # enable experimentation and fine-tuning
    top_p: 0.9 # enable experimentation and fine-tuning
    cache: false # control prompt caching
    max_tokens: 8192 # allow overriding max tokens
    additional_headers: # enables addition of headers to help with bleeding edge features that are not integrated in code;
      anthropic-version: 2023-06-01
    ratelimit: # setup rate-limiting
      type: simple
      config:
        requests:
          limit: 80 # Maximum API calls per period
          period_seconds: 60 # Time window in seconds (i.e. 1 minute)
        tokens:
          limit: 80000 # Maximum input tokens per period
          period_seconds: 60
        retry:
          delay_seconds: 60 # Wait time upon a rate-limit error
          max_retries: 3
  - name: "claude-openrouter"
    provider: "openai"
    api: "https://openrouter.ai/api/v1/chat/completions"
    model: "anthropic/claude-3.5-sonnet:beta"
    cache: false
    max_tokens: 8192
    ratelimit:
      type: token_bucket
      config:
        capacity: 80 # Maximum burst capacity (i.e. tokens available)
        refill_rate: 80 # Number of tokens added per period (e.g. per minute)
        period_seconds: 60 # The time window for refilling tokens
        retry:
          delay_seconds: 60
          max_retries: 3
```
